# Hexo配置
## 文档：https://hexo.io/zh-cn/docs/configuration
## 源代码：https://github.com/hexojs/hexo/

# 站点设置
title: 夕の書架
subtitle: ^_^
description: 程序员一枚~
keywords: 
author: 夕
language: zh-CN
timezone: 'Asia/Shanghai'



# URL设置
## 在此处设置您的站点URL。例如使用GitHub Page时，设置为'https://username.github.io/project'
url: https://blog.misyakuji.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # 设置为false可移除永久链接末尾的'index.html'
  trailing_html: true #设置为false可移除永久链接末尾的'.html'

# 目录设置
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作设置
new_post_name: :title.md # 新文章的文件名
default_layout: post
titlecase: false # 转换标题为标题格式
external_link:
  enable: true # 在新标签页中打开外部链接
  field: site # 应用于整个站点
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: false
highlight:
  enable: false #停用默认高光代码
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false #停用默认高光代码
  preprocess: true
  line_number: true
  tab_replace: ''

# 主页设置
# path: 博客索引页的根路径。(默认值 = '')
# per_page: 每页显示的文章数。(0 = 禁用分页)
# order_by: 文章排序方式。(默认按日期倒序排列)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类与标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间格式
## Hexo使用Moment.js解析和显示日期
## 可根据以下格式自定义日期显示
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option支持'mtime', 'date', 'empty'
updated_option: 'mtime'

# 分页设置
## 设置per_page为0可禁用分页
per_page: 10
pagination_dir: page

# 包含/排除文件
## include:/exclude: 选项仅适用于'source/'目录
include:
exclude:
ignore:

# 扩展设置
## 插件：https://hexo.io/plugins/
## 主题：https://hexo.io/themes/
theme: shokax

# 部署设置
## 文档：https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/misyakuji/misyakuji.github.io
  branch: master

markdown:
  render: # 渲染器设置
    html: false # 过滤HTML标签
    xhtmlOut: true # 使用'/'闭合单标签（如<br />）
    breaks: true # 转换段落中的'\n'为<br>
    linkify: true # 自动转换类似URL的文本为链接
    typographer:
    quotes: "“”‘’"
  plugins: # markdown-it插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录及锚点应用的class名称，shoka系主题必须如此设置
          tocClassName: "toc"
          anchorClassName: "anchor"
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得太多了"

feed:
  limit: 20
  order_by: "-date"
  tag_dir: false
  category_dir: false
  rss:
    enable: true
    template: "node_modules/hexo-theme-shokax/layout/_alternate/rss.ejs"
    output: "rss.xml"
  atom:
    enable: true
    template: "node_modules/hexo-theme-shokax/layout/_alternate/atom.ejs"
    output: "atom.xml"
  jsonFeed:
    enable: true
    template: "node_modules/hexo-theme-shokax/layout/_alternate/json.ejs"
    output: "feed.json"

minify:
  js:
    enable: false # ShokaX 自带 esbuild 优化，不建议开启，其他主题建议开启
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  css:
    enable: true # 开启 CSS 优化
    options:
      targets: ">= 0.5%" # browserslist 格式的 target
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  html:
    minifier: html-minifier
    enable: true # 开启 HTML 优化
    options:
      comments: false # 是否保留注释内容
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  image:
    enable: false # 开启图片预处理和自动 WebP 化
    options:
      avif: false
      webp: true # 预留配置项，现版本无作用
      quality: 80 # 质量，支持1-100的整数、lossless或nearLossless
      effort: 2 # CPU 工作量，0-6之间的整数(越低越快)
      replaceSrc: false # 自动替换生成html中的本地图片链接为webp链接
      # 对于使用 CI 工作流部署的用户，请注意本配置可能导致图片 404，如果出现请关闭
      # 我们更建议使用 Service Worker 来在用户侧实现 replaceSrc 的功能，这将能够以一种侵入式更小的方式实现链接替换
    exclude: